name: Java CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:

  build:
    name: Build and test project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with: 
        name: builded artifacts
        path: public/
      
  publish:
    name: Publish docker image to github packages
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download built artifact
      uses: actions/download-artifact@master
      with:
        name: builded artifacts
        path: public
    - name: Build, Tag, Push
      uses: mattdavis0351/actions/docker-gpr@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: test
